site_name: Innovation Workshop Wiki
site_description: Equipment SOPs, Safety, and Guides for CNSI Workshops

theme:
  name: material
  logo: assets/IW-logo.png
  palette:
      scheme: slate
      primary: teal
      accent: orange
      
  features:
    - navigation.instant   # Fast page loading without full reloads
    - navigation.tracking  # Updates URL hash as you scroll through headings
    #- navigation.tabs      # Displays top-level navigation as tabs
    - navigation.sections  # Groups sidebar items under sections
    - navigation.top       # Adds a "Back to top" button
    - search.suggest       # Auto-completes search terms
    - search.highlight     # Highlights search results on the page
    - content.code.copy    # Adds a copy button to code blocks

  extensions:
    - attr_list

nav:
  - Home: index.md
  - About: about.md
  - Access & Training: access-and-training.md
  - Tool Pages:
      - 3D Printing:
          - Bambu X1C: tools/3d-printing/bambu-x1c.md
          - Bambu H2D: tools/3d-printing/bambu-h2d.md
          - Form 4: tools/3d-printing/form4.md
          - Form 3: tools/3d-printing/form3.md
      - Machining:
          - Haas CNC Super Mini Mill: tools/machining/haas.md
          - Vertical Mill: tools/machining/mill.md
          - Lathe: tools/machining/lathe.md
          - Drill Press: tools/machining/drill-press.md
          - Band Saw: tools/machining/band-saw.md
          - Wazer Waterjet: tools/machining/wazer/md
          - ThunderLaser Nova 35: tools/machining/laser-cutter.md
      - Polymer Casting:
          - Thinky Planetary Mixer: tools/polymer-casting/thinky.md
          - Silanization Chamber: tools/polymer-casting/silane.md
          - Vacuum Chambers: tools/polymer-casting/vacuum-chambers.md
          - Plasma Chamber: tools/polymer-casting/plasma.md
          - UV Ozone Chamber: tools/polymer-casting/uv-ozone.md
          - Convection Ovens: tools/polymer-casting/ovens.md
  - Lab Safety: safety.md
  - Contact & People: people.md
